spring.application.name=backend

# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/textile_garment_new_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Sak/2005/br
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ==========================================
# SERVER
# ==========================================

server.port=8080


# ==========================================
# AUTHENTICATION TOKEN
# ==========================================

app.auth.secret=textile-garment-management-system-secret-key-2026
app.auth.expiration-ms=28800000